export const recipes = [
  {
    title: 'Banana bread',
    specs: { time: '75min', temp: '180°', serving: 8 },
    tags: ['Sweet'],
    ingredients: [
      { ingredient: 'Flour', quantity: '250 g' },
      { ingredient: 'Baking soda', quantity: '1 tsp' },
      { ingredient: 'Salt', quantity: '1/4 tsp' },
      { ingredient: 'Cinnamon', quantity: '1/2 tsp' },
      { ingredient: 'Butter', quantity: '115 g' },
      { ingredient: 'Brown sugar', quantity: '150 g' },
      { ingredient: 'Eggs', quantity: '2' },
      { ingredient: 'Yoghurt', quantity: '80 g' },
      { ingredient: 'Ripe bananas', quantity: '4' },
      { ingredient: 'Vanilla extract', quantity: '1 tsp' },
      { ingredient: 'Nuts' },
    ],
    steps: [
      'Grease the mold',
      'Put the butter to heat until liquid',
      'Mash the bananas',
      'Whisk the flour, baking soda, salt, and cinnamon in a bowl',
      'In another bowl, beat the butter and brown sugar together until smooth and creamy',
      'Add the eggs one at a time, beating continously',
      'Add the yogurt, mashed bananas, and vanilla extract',
      'Preheat the oven at 180°',
      'Slowly combine the flour mix into the wet ingredients, beating until no flour pockets remain',
      'Add the nuts',
      'Put the mixture in the mold',
      'Cook for 1h',
      'Check the cooking - a knife coming out clean of the bread',
      'Remove from the oven and let it cool',
      'Enjoy and keep up to 2 days in a room, 1 week in the fridge',
    ],
  },
]
